version: '3'

networks:
  app-tier:
    driver: bridge

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    networks:
      - app-tier
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: comverga
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
    volumes:
      - ./db_scheme:/docker-entrypoint-initdb.d
    networks:
      - app-tier